spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8085
dubbo:
  application:
    name: provider-service
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181